#  without nginx

# # FROM node:14-alpine

# # WORKDIR /trainee_frontend

# # COPY ./package.json .

# # RUN npm install

# # COPY .  .

# # EXPOSE 3000 

# # CMD ["npm" , "start"]

# with nginx

FROM node:14-alpine AS build

WORKDIR /trainee_frontend_build_dev

COPY package.json .

RUN npm install

COPY . .

RUN npm run build


FROM nginx:1.23-alpine

WORKDIR /usr/share/nginx/html

COPY ./default.conf /etc/nginx/conf.d/default.conf

COPY --from=build /trainee_frontend_build_dev/build .

CMD ["nginx", "-g", "daemon off;"]